### ISSUE TITLE
Run Gemma models with ollama-python

### ISSUE THREAD

**Issue by sitammeur** [google-gemma/cookbook#103]
### Description of the feature request:

In Gemma cookbooks, we already have a notebook named `Run_with_Ollama.ipynb`. In this notebook, we find the guide on how to run the Gemma family of models with Ollama. But now recently we have the `ollama-python` package [here](https://github.com/ollama/ollama-python) with which we can run gemma models too. We can therefore think of this feature request as a sequel to our current notebook.

### What problem are you trying to solve with this feature?

The simplest method for integrating Python 3.8+ projects with [Ollama] is to use the [Ollama Python](https://github.com/ollama/ollama) library. Thus, using the above-described thought notebook, we can demonstrate how to use the Ollama Python library to run the Gemma family of models. It offers a wide range of options for chatting with models, including standard chat messages and streaming responses. It also offers custom client options and an async client. People can further benefit from these features that are to be displayed in the notebook when working on their projects.

### Any other information you'd like to share?

This is the very intro work on this notebook for supporting my thought, which further to be enhanced before making the actual pull request.

Notebook Link: https://colab.research.google.com/drive/1knkSItPepE6V0KhhTimbG14nzHz20Mei?usp=sharing

cc: @windmaple

**Comment by windmaple** [comment]
This sounds good. Can you send a PR based on your intro notebook? Happy to merge it.

**Comment by bebechien** [comment]
PR has been merged, Closing this issue. Thanks, Sitam!
