### ISSUE TITLE
Continued pretraining of Gemma models

### ISSUE THREAD

**Issue by amankumarhal** [google-gemma/cookbook#46]
### Description of the feature request:

Hi, I have domain-specific dataset, and I was wondering if there could be a codebase for additional/continued pretraining of gemma-2 models.

### What problem are you trying to solve with this feature?

Making generative models adapt to domain-specific data.

**Comment by windmaple** [comment]
That'd be great! Please follow the [steps](https://github.com/google-gemini/gemma-cookbook/blob/main/CONTRIBUTING.md#pr-checklist) and send PR.
