### ISSUE TITLE
Any continue Pretrain in TPU

### ISSUE THREAD

**Issue by msamwelmollel** [google-gemma/cookbook#57]
### Description of the feature request:

I would like the cookbook to add continue pre train in TPU

**Comment by windmaple** [comment]
Added to the wishlist.

**Comment by windmaple** [comment]
Actually do you have access to TPU v5? If not, it's a moot point

v3/v4 (32G HBM per chip) will OOM w/ full parameter tuning for Gemma 7B. 2B doesn't work either since the sharding is diff.
