### ISSUE TITLE
remove the HF token in PaliGemma/PaliGemma-on-Android/Python_Server/apiserver/api/test.py

### ISSUE THREAD

**Issue by windmaple** [google-gemma/cookbook#67]
### Description of the bug:

@NSTiwari could you remove the HF token in PaliGemma/PaliGemma-on-Android/Python_Server/apiserver/api/test.py and put in a env var or sth. This is raising a GitHub security warning

**Comment by NSTiwari** [comment]
@windmaple: PR #73 created. Please review and merge.

**Comment by windmaple** [comment]
Thank you!
