### ISSUE TITLE
Fine-tune Paligemma model for segmentation task

### ISSUE THREAD

**Issue by anamabo** [google-gemma/cookbook#99]
### Description of the bug:

Hello:
I want to use Paligemma to segment water in satellite images. However, I haven't been able to find any documentation on how to scale the points inside my mask to be able to use them in Paligemma. 
So far I have done the following:

Variables: 
(x, y):  is 1 point of the 8 needed. 
w, h = width, height of the bounding box

I do the following transformation of x and y:

x_paligemma = x*w / 64
y_paligemma = y*h / 64

When I try to fine-tune the Paligemma model on this transformation, I obtain empty predictions. Could you please tell me how can I prepare the segmentation points to have results in my model?

Thank you so much for your response!

**Comment by windmaple** [comment]
Why do you need this transformation? It's not quite clear.

**Comment by windmaple** [comment]
Closing as stale
